[ignore]
  ./node_modules/
  ./*.test.js
  .*/ImgSearch/index.jsx
  .*/App.jsx
[include]
  ./src/
[lints]
all=warn
untyped-type-import=off
[options]
emoji=true
esproposal.export_star_as=enable
module.file_ext=.js
module.file_ext=.jsx
module.file_ext=.json
module.file_ext=.css
module.file_ext=.scss
module.name_mapper.extension='css' -> 'empty/object'
module.name_mapper.extension='scss' -> 'empty/object'
[strict]
